GIR.Sigim/GIR.Sigim.Presentation.WebUI/Areas/Financeiro/Controllers/CentroCustoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GIR.Sigim.Application.DTO.Financeiro;
using GIR.Sigim.Application.Service.Financeiro;
using GIR.Sigim.Infrastructure.Crosscutting.Notification;
using GIR.Sigim.Presentation.WebUI.Controllers;

namespace GIR.Sigim.Presentation.WebUI.Areas.Financeiro.Controllers
{
    public class CentroCustoController : BaseController
    {
        private ICentroCustoAppService centroCustoAppService;

        public CentroCustoController(ICentroCustoAppService centroCustoAppService, MessageQueue messageQueue)
            : base(messageQueue)
        {
            this.centroCustoAppService = centroCustoAppService;
        }

        [HttpPost]
        public ActionResult ValidaCentroCustoPorUsuario(string codigo, string modulo, bool somenteNivelFolha)
        {
            var centroCusto = centroCustoAppService.ObterPeloCodigo(codigo);
            if (!string.IsNullOrEmpty(codigo))
            {

                if ((somenteNivelFolha && !centroCustoAppService.EhCentroCustoUltimoNivelValido(centroCusto))
                    || !centroCustoAppService.EhCentroCustoValido(centroCusto)
                    || !centroCustoAppService.UsuarioPossuiAcessoCentroCusto(centroCusto, Usuario.Id, modulo))
                {
                    var msg = messageQueue.GetAll()[0].Text;
                    messageQueue.Clear();
                    return Json(new { ehValido = false, errorMessage = msg, descricao = string.Empty });
                }
                return Json(new { ehValido = true, errorMessage = string.Empty, descricao = centroCusto.Descricao });
            }
            return Json(new { ehValido = true, errorMessage = string.Empty, descricao = string.Empty });
        }

        [HttpPost]
        public ActionResult TreeView()
        {
            var model = centroCustoAppService.ListarRaizesAtivas();
            ViewBag.FirstNode = "Centro de Custo";
            return View("~/Views/Shared/EditorTemplates/TreeView.cshtml",model);
        }
    }
}

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Areas/Financeiro/Controllers/ClasseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GIR.Sigim.Application.DTO.Financeiro;
using GIR.Sigim.Application.Service.Financeiro;
using GIR.Sigim.Infrastructure.Crosscutting.Notification;
using GIR.Sigim.Presentation.WebUI.Controllers;

namespace GIR.Sigim.Presentation.WebUI.Areas.Financeiro.Controllers
{
    public class ClasseController : BaseController
    {
        private IClasseAppService classeAppService;

        public ClasseController(IClasseAppService classeAppService, MessageQueue messageQueue)
            : base(messageQueue)
        {
            this.classeAppService = classeAppService;
        }

        [HttpPost]
        public ActionResult ValidaClasse(string codigo, int orcamentoId, bool somenteNivelFolha)
        {
            var classe = classeAppService.ObterPeloCodigoEOrcamento(codigo, orcamentoId);
            if (!string.IsNullOrEmpty(codigo))
            {
                //if (somenteNivelFolha && !classeAppService.EhClasseUltimoNivelValida(classe, orcamentoId)
                //    || !classeAppService.EhClasseValida(classe, orcamentoId))
                if (somenteNivelFolha && !classeAppService.EhClasseUltimoNivelValida(codigo, orcamentoId)
                || !classeAppService.EhClasseValida(classe, orcamentoId))
                {
                    var msg = messageQueue.GetAll()[0].Text;
                    messageQueue.Clear();
                    return Json(new { ehValido = false, errorMessage = msg, descricao = string.Empty });
                }
                return Json(new { ehValido = true, errorMessage = string.Empty, descricao = classe.Descricao });
            }
            return Json(new { ehValido = true, errorMessage = string.Empty, descricao = string.Empty });
        }

        [HttpPost]
        public ActionResult TreeView(int? orcamentoId)
        {
            var model = classeAppService.ListarPeloOrcamento(orcamentoId);
            ViewBag.FirstNode = "Classe";
            return View("~/Views/Shared/EditorTemplates/TreeView.cshtml",model);
        }
    }
}

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Controllers/ClienteFornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GIR.Sigim.Infrastructure.Crosscutting.Notification;
using GIR.Sigim.Application.Service.Sigim;
using GIR.Sigim.Application.Enums;
using GIR.Sigim.Application.Filtros.Sigim;
using GIR.Sigim.Application.DTO.Sigim;

namespace GIR.Sigim.Presentation.WebUI.Controllers
{
    public class ClienteFornecedorController : BaseController
    {
        private IClienteFornecedorAppService clienteFornecedorAppService;

        public ClienteFornecedorController(IClienteFornecedorAppService clienteFornecedorAppService,
                                           MessageQueue messageQueue)
            : base(messageQueue)
        {
            this.clienteFornecedorAppService = clienteFornecedorAppService;
        }

        [HttpPost]
        public ActionResult ListarClienteFornecedorPorNome(string nome,
                                                           ClienteFornecedorModuloAutoComplete clienteFornecedorModulo,
                                                           SituacaoAutoComplete situacao)
        {
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.Contrato){
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    var model = clienteFornecedorAppService.ListarClienteContratoAtivosPorNome(nome);
                    return Json(model);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.OrdemCompra){
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    var model = clienteFornecedorAppService.ListarClienteOrdemCompraAtivosPorNome(nome);
                    return Json(model);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.APagar)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    var model = clienteFornecedorAppService.ListarClienteAPagarAtivosPorNome(nome);
                    return Json(model);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.AReceber)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    var model = clienteFornecedorAppService.ListarClienteAReceberAtivosPorNome(nome);
                    return Json(model);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.Todos)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    var model = clienteFornecedorAppService.ListarClienteTodosModulosAtivosPorNome(nome);
                    return Json(model);
                }
            }

            return Json(null);
        }

        [HttpPost]
        public ActionResult PesquisarClienteFornecedor(ClienteFornecedorPesquisaFiltro filtro,
                                                       ClienteFornecedorModuloAutoComplete clienteFornecedorModulo,
                                                       SituacaoAutoComplete situacao)
        {
            int totalRegistros = 0;
            List<ClienteFornecedorDTO> result = null;
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.Contrato)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    result = clienteFornecedorAppService.PesquisarClientesDeContratoAtivosPeloFiltro(filtro, out totalRegistros);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.OrdemCompra)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    result = clienteFornecedorAppService.PesquisarClientesDeOrdemCompraAtivosPeloFiltro(filtro, out totalRegistros);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.APagar)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    result = clienteFornecedorAppService.PesquisarClientesAPagarAtivosPeloFiltro(filtro, out totalRegistros);
                }
            }
            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.AReceber)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    result = clienteFornecedorAppService.PesquisarClientesAReceberAtivosPeloFiltro(filtro, out totalRegistros);
                }
            }

            if (clienteFornecedorModulo == ClienteFornecedorModuloAutoComplete.Todos)
            {
                if (situacao == SituacaoAutoComplete.Ativo)
                {
                    result = clienteFornecedorAppService.PesquisarClientesDeTodosOsModulosAtivosPeloFiltro(filtro, out totalRegistros);
                }
            }


            if (result.Any())
            {
                var listaViewModel = CreateListaViewModel(filtro, totalRegistros, result);
                return PartialView("ListaPesquisaPartial", listaViewModel);
            }
            return PartialView("_EmptyListPartial");
        }

    }
}

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Controllers/MaterialClasseInsumoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GIR.Sigim.Infrastructure.Crosscutting.Notification;
using GIR.Sigim.Application.Service.Sigim;

namespace GIR.Sigim.Presentation.WebUI.Controllers
{
    public class MaterialClasseInsumoController : BaseController
    {
        private IMaterialClasseInsumoAppService materialClasseInsumoAppService;

        public MaterialClasseInsumoController(IMaterialClasseInsumoAppService materialClasseInsumoAppService, 
                                              MessageQueue messageQueue)
            : base(messageQueue)
        {
            this.materialClasseInsumoAppService = materialClasseInsumoAppService;
        }

        [HttpPost]
        public ActionResult ValidaClasseInsumo(string codigo, bool somenteNivelFolha)
        {
            var classeInsumo = materialClasseInsumoAppService.ObterPeloCodigo(codigo);
            if (!string.IsNullOrEmpty(codigo))
            {
                if (somenteNivelFolha && !materialClasseInsumoAppService.EhClasseInsumoUltimoNivelValida(classeInsumo)
                    || !materialClasseInsumoAppService.EhClasseInsumoValida(classeInsumo))
                {
                    var msg = messageQueue.GetAll()[0].Text;
                    messageQueue.Clear();
                    return Json(new { ehValido = false, errorMessage = msg, descricao = string.Empty });
                }
                return Json(new { ehValido = true, errorMessage = string.Empty, descricao = classeInsumo.Descricao });
            }
            return Json(new { ehValido = true, errorMessage = string.Empty, descricao = string.Empty });
        }


        [HttpPost]
        public ActionResult TreeView()
        {
            var model = materialClasseInsumoAppService.ListarRaizes();
            ViewBag.FirstNode = "Classe Insumo";
            return View("~/Views/Shared/EditorTemplates/TreeView.cshtml",model);
        }

    }
}

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Views/Shared/EditorTemplates/CentroCusto.cshtml
@model GIR.Sigim.Application.DTO.Financeiro.CentroCustoDTO

<section class="@ViewBag.sectionClass">
    @{
        string labelText = !string.IsNullOrEmpty(ViewBag.labelText) ? ViewBag.labelText : Html.DisplayNameFor(m => m.Codigo).ToString();
    }
    @Html.LabelFor(m => m.Codigo, labelText, new { @class = "label" })
    <div class="input-group">
        <label class="input">
            @{
                string cssClass = (ViewBag.required as bool? ?? false) ? "required" : string.Empty;
            }
            @Html.TextBoxFor(m => m.Codigo, new { @class = cssClass })
        </label>
        <a id="BtnShowModalPanel_@Html.IdFor(m => m.Codigo)" data-toggle="modal" href="#@Html.IdFor(m => m.Codigo)_ModalPanel" class="button-icon input-group-addon"><i class="fa fa-lg fa-sitemap"></i></a>
    </div>
    @Html.ValidationMessageFor(m => m.Codigo, "", new { @id = Html.IdFor(m => m.Codigo) + "_ValidationMessage", @class = "note note-error" })
</section>
<section class="@ViewBag.sectionClass">
    <label class="label" for="fname">&nbsp;</label>
    <label class="input">
        @Html.TextBoxFor(m => m.Descricao, new { @readonly = "", @class = "readonly" })
    </label>
</section>

<div class="modal fade" id="@Html.IdFor(m => m.Codigo)_ModalPanel" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Centro de Custo
                </h4>
            </div>
            <fieldset style="border-bottom:solid 1px #CCCCCC; padding:14px;">
                <div class="row">
                    <section class="col col-12" style="margin-bottom:0;">
                        <label class="input">
                            <input id="filtro@(Html.IdFor(m => m.Descricao))" name="filtro@(Html.IdFor(m => m.Descricao))" type="text" placeholder="Digite aqui a descrição">
                        </label>
                    </section>
                </div>
            </fieldset>
            <div id="@Html.IdFor(m => m.Codigo)_ModalBody" class="modal-body no-padding sigimModalBody">
                <div id="@Html.IdFor(m => m.Codigo)_tree" class="tree smart-form">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    @{
        bool? somenteNivelFolha = ViewBag.somenteNivelFolha as bool? ?? false;
        bool? podeEditar = ViewBag.podeEditar as bool? ?? true;
    }
    $(document).ready(function () {
        $(document).on("change", "#@Html.IdFor(m => m.Codigo)", function () {
            validaCentroCusto();
        });

        var timeout = '';
        $(document).on('input', '#filtro@(Html.IdFor(m => m.Descricao))', function () {
            clearTimeout(timeout);
            var descricao = $(this).val();
            timeout = setTimeout(function () {
                resetTreeView($('#@Html.IdFor(m => m.Codigo)_tree.tree'));
                highlightNodes($('#@Html.IdFor(m => m.Codigo)_tree.tree'), descricao);
            }, 250);
        });

        $(document).on("show.bs.modal", "#@Html.IdFor(m => m.Codigo)_ModalPanel", function () {
            $('#filtro@(Html.IdFor(m => m.Descricao))').val('');
            $('#@Html.IdFor(m => m.Codigo)_tree').html('');

            $.ajax({
                type: 'POST',
                url: '@Url.Action("TreeView", "CentroCusto", new { area = "Financeiro" })',
                cache: false
            })
            .success(function (result) {
                $('#@Html.IdFor(m => m.Codigo)_tree').html(result);

                $('#@Html.IdFor(m => m.Codigo)_tree.tree > ul').attr('role', 'tree').find('ul').attr('role', 'group');

                $('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li:has(ul)').addClass('parent_li').attr('role', 'treeitem').find(' > span').on('click', function (e) {
                    var children = $(this).parent('li.parent_li').find(' > ul > li');
                    if (children.is(':visible')) {
                        children.hide('fast');
                        $(this).find(' > i').addClass("fa-plus-circle").removeClass("fa-minus-circle");
                    } else {
                        children.show('fast');
                        $(this).find(' > i').addClass("fa-minus-circle").removeClass("fa-plus-circle");
                    }
                    e.stopPropagation();
                });

                $('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li').not(':has(ul)').find(' > span').css({ cursor: 'pointer' }).on('click', function (e) {
                    $('#@Html.IdFor(m => m.Codigo)').val($(this).data("codigo-centro-custo")).change();
                    $('#@Html.IdFor(m => m.Codigo)_ModalPanel').modal('hide');
                });

                @if (!somenteNivelFolha.Value) {
                    @:$('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li:has(ul)').find(' > span').css({ cursor: 'pointer' }).on('dblclick', function (e) {
                    @:  $('#@Html.IdFor(m => m.Codigo)').val($(this).data("codigo-centro-custo")).change();
                    @:  $('#@Html.IdFor(m => m.Codigo)_ModalPanel').modal('hide');
                    @:});
                }

                highlightNode($('#@Html.IdFor(m => m.Codigo)_tree.tree'), $('#@Html.IdFor(m => m.Codigo)').val());
            });
        });

        @if (!podeEditar.Value)
        {
            @:$("#@Html.IdFor(m => m.Codigo)").attr("readonly", true);
            @:$("#@Html.IdFor(m => m.Codigo)").addClass("readonly");
            @:$("#BtnShowModalPanel_@Html.IdFor(m => m.Codigo)").attr('href', 'javascript:void(0);');
            @:$("#BtnShowModalPanel_@Html.IdFor(m => m.Codigo)").removeAttr('data-toggle');
        }
    });

    function validaCentroCusto() {
        var isValid = false;
        var codigoCentroCusto = $("#@Html.IdFor(m => m.Codigo)").val();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("ValidaCentroCustoPorUsuario", "CentroCusto", new { area = "Financeiro" })',
            cache: false,
            async: false,
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({
                codigo: codigoCentroCusto,
                modulo: '@GIR.Sigim.Application.Resource.Sigim.NomeModulo.OrdemCompra',
                somenteNivelFolha: '@somenteNivelFolha.Value'
            })
        })
        .success(function (result) {
            showErrorMessage(getErrorMessageContainer('@Html.NameFor(m => m.Codigo)'), result.errorMessage);
            $('#@Html.IdFor(m => m.Descricao)').val(result.descricao);
            isValid = result.ehValido;
        });

        $.event.trigger({
            type: "centroCustoValidado",
            codigo: codigoCentroCusto,
            isValid: isValid
        });

        return isValid;
    }

    function notificarObrigatoriedadeCentroCusto() {
        smartAlert("Erro", "Escolha o Centro de Custo!", "error");
    }
</script>

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Views/Shared/EditorTemplates/ClasseInsumo.cshtml
@model GIR.Sigim.Application.DTO.Sigim.MaterialClasseInsumoDTO

<section class="@ViewBag.sectionClass">
    @{
        string labelText = !string.IsNullOrEmpty(ViewBag.labelText) ? ViewBag.labelText : Html.DisplayNameFor(m => m.Codigo).ToString();
    }
    @Html.LabelFor(m => m.Codigo, labelText, new { @class = "label" })
    <div class="input-group">
        <label class="input">
            @{
                string cssClass = (ViewBag.required as bool? ?? false) ? "required" : string.Empty;
            }
            @Html.TextBoxFor(m => m.Codigo, new { @class = cssClass })
        </label>
        <a id="BtnShowModalPanel_@Html.IdFor(m => m.Codigo)" data-toggle="modal" href="#@Html.IdFor(m => m.Codigo)_ModalPanel" class="button-icon input-group-addon"><i class="fa fa-lg fa-sitemap"></i></a>
    </div>
    @Html.ValidationMessageFor(m => m.Codigo, "", new { @id = Html.IdFor(m => m.Codigo) + "_ValidationMessage", @class = "note note-error" })
</section>
<section class="@ViewBag.sectionClass">
    <label class="label" for="fname">&nbsp;</label>
    <label class="input">
        @Html.TextBoxFor(m => m.Descricao, new { @readonly = "", @class = "readonly" })
    </label>
</section>

<div class="modal fade" id="@Html.IdFor(m => m.Codigo)_ModalPanel" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Classe Insumo
                </h4>
            </div>
            <fieldset style="border-bottom:solid 1px #CCCCCC; padding:14px;">
                <div class="row">
                    <section class="col col-12" style="margin-bottom:0;">
                        <label class="input">
                            <input id="filtro@(Html.IdFor(m => m.Descricao))" name="filtro@(Html.IdFor(m => m.Descricao))" type="text" placeholder="Digite aqui a descrição">
                        </label>
                    </section>
                </div>
            </fieldset>
            <div id="@Html.IdFor(m => m.Codigo)_ModalBody" class="modal-body no-padding sigimModalBody">
                <div id="@Html.IdFor(m => m.Codigo)_tree" class="tree smart-form">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    @{
        bool? somenteNivelFolha = ViewBag.somenteNivelFolha as bool? ?? false;
    }

    $(document).ready(function () {
        $(document).on("change", "#@Html.IdFor(m => m.Codigo)", function () {
            validaClasseInsumo();
        });

        var timeout = '';
        $(document).on('input', '#filtro@(Html.IdFor(m => m.Descricao))', function () {
            clearTimeout(timeout);
            var descricao = $(this).val();
            timeout = setTimeout(function () {
                resetTreeView($('#@Html.IdFor(m => m.Codigo)_tree.tree'));
                highlightNodes($('#@Html.IdFor(m => m.Codigo)_tree.tree'), descricao);
            }, 250);
        });


        $(document).on("show.bs.modal", "#@Html.IdFor(m => m.Codigo)_ModalPanel", function () {
            $('#filtro@(Html.IdFor(m => m.Descricao))').val('');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("TreeView", "MaterialClasseInsumo", new { area = "" })',
                cache: false
            })
            .success(function (result) {
                $('#@Html.IdFor(m => m.Codigo)_tree').html(result);

                $('#@Html.IdFor(m => m.Codigo)_tree.tree > ul').attr('role', 'tree').find('ul').attr('role', 'group');

                $('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li:has(ul)').addClass('parent_li').attr('role', 'treeitem').find(' > span').on('click', function (e) {
                    var children = $(this).parent('li.parent_li').find(' > ul > li');
                    if (children.is(':visible')) {
                        children.hide('fast');
                        $(this).find(' > i').removeClass().addClass('fa fa-lg fa-plus-circle');
                    } else {
                        children.show('fast');
                        $(this).find(' > i').removeClass().addClass('fa fa-lg fa-minus-circle');
                    }
                    e.stopPropagation();
                });

                $('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li').not(':has(ul)').find(' > span').css({ cursor: 'pointer' }).on('click', function (e) {
                    $('#@Html.IdFor(m => m.Codigo)').val($(this).data("codigo-centro-custo")).change();
                    $('#@Html.IdFor(m => m.Codigo)_ModalPanel').modal('hide');
                });

                @if (!somenteNivelFolha.Value) {
                    @:$('#@Html.IdFor(m => m.Codigo)_tree.tree').find('li:has(ul)').find(' > span').css({ cursor: 'pointer' }).on('dblclick', function (e) {
                    @:  $('#@Html.IdFor(m => m.Codigo)').val($(this).data("codigo-centro-custo")).change();
                    @:  $('#@Html.IdFor(m => m.Codigo)_ModalPanel').modal('hide');
                    @:});
                }
            });
        });
    });

    function validaClasseInsumo() {
        var isValid = false;
        var codigoClasseInsumo = $("#@Html.IdFor(m => m.Codigo)").val();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("ValidaClasseInsumo", "MaterialClasseInsumo", new { area = "" })',
            cache: false,
            async: false,
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({
                codigo: codigoClasseInsumo,
                somenteNivelFolha: '@somenteNivelFolha.Value'
            })
        })
        .success(function (result) {
            showErrorMessage(getErrorMessageContainer('@Html.NameFor(m => m.Codigo)'), result.errorMessage);
            $('#@Html.IdFor(m => m.Descricao)').val(result.descricao);
            isValid = result.ehValido;
        });

        return isValid;
    }
</script>

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Views/Shared/EditorTemplates/Imprimir.cshtml
@using GIR.Sigim.Application.Adapter;
@using GIR.Sigim.Application.DTO.Sigim;
@model bool
@{
    string disableBtnImprimir = string.Empty;
    if (!Model)
    {
        disableBtnImprimir = "disabled";
    }
}
<a data-toggle="modal" href="#FormatoImpressao_ModalPanel" id="btnImprimir" class="btn btn-primary @disableBtnImprimir">Imprimir</a>
@if (Model) {
    <div class="modal fade" id="FormatoImpressao_ModalPanel" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title">
                        Formato do Arquivo para Impressão
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col col-12">
                            @{
                                var listaFormatoExportacaoArquivo = new SelectList(typeof(FormatoExportacaoArquivo).ToItemListaDTO(), "Id", "Descricao", (int)FormatoExportacaoArquivo.PDF);
                                foreach (var item in listaFormatoExportacaoArquivo)
	                            {
                                    var itemChecked = string.Empty;
                                    if (item.Selected)
                                    {
                                        itemChecked = "checked=\"checked\"";
                                    }
                                    @:<label class="radio">
							        @:  <input type="radio" name="formatoExportacaoArquivo" value="@item.Value" @itemChecked>
							        @:  <i></i>@item.Text
                                    @:</label>
	                            }
                            }
					    </div>
                    </div>
                </div>
                <div class="modal-footer">
					<button type="button" id="btnConfirmarImpressao" class="btn btn-primary" data-dismiss="modal">
						Ok
					</button>
				</div>
            </div>
        </div>
        <script type="text/javascript">
            var parametrosUrlImpressao = '';
            $(document).ready(function () {
                $(document).on("show.bs.modal", "#FormatoImpressao_ModalPanel", function (e) {
                    $.event.trigger({
                        type: "showFormatoImpressaoModalPanel",
                        event: e
                    });
                });

                $("#btnConfirmarImpressao").on("click", function () {
                    window.open('@ViewBag.url?formato=' + $("input:radio[name=formatoExportacaoArquivo]:checked").val() + parametrosUrlImpressao);
                });
            });
        </script>
    </div>
}

GIR.Sigim/GIR.Sigim.Presentation.WebUI/Views/Shared/EditorTemplates/TreeNode.cshtml
@model GIR.Sigim.Application.DTO.Sigim.TreeNodeDTO

<li style="@ViewBag.style">
    @{
        var cssClass = "icon-leaf";
        if (Model.ListaFilhos.Any())
        {
            cssClass = "fa fa-lg fa-plus-circle";
        }
    }
    <span data-codigo-centro-custo="@Model.Codigo"><i class="@cssClass"></i> @Model.Codigo - @Model.Descricao</span>

    @if (Model.ListaFilhos.Any())
    {
        <ul>
            @foreach (var item in Model.ListaFilhos)
            {
                @Html.Partial("~/Views/Shared/EditorTemplates/TreeNode.cshtml", item, new ViewDataDictionary { { "style", "display: none" } })
            }
        </ul>
    }
</li>